version: '3.1'
services:
  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - http 
  odoo:
    image: odoo:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=odoo"
      - "traefik.frontend.rule=Host:odoo.localhost"
      - "traefik.port=8069"
      - "traefik.docker.network=http"
    networks:
      - http
      - internal
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - internal
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.backend=adminer"
      - "traefik.frontend.rule=Host:adminer.localhost"
      - "traefik.port=8080"
      - "traefik.docker.network=http"
    networks:
      - http
      - internal

networks:
  http:
    external: true
  internal:
    internal: true
