version: '3.1'
services:
  odoo:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
